### PR TITLE
#20 bugfix and new Band-Pass Biquad Filter

### PR DESCRIPTION
**Pull request by davidgovea**
Fixed a bug in #20 in the BiquadFilter.reset method..
`self.inputs = self.outputs = [0,0]` wasn't producing expected results

Added new BandPass filter & updated test page with 2 BPF tests

### CODE REVIEW

**Comment by jussi-kalliokoski** [comment]
Sorry for the trouble. :)

**Comment by jussi-kalliokoski** [comment]
Your test cases make mine pale in comparison. :D

**Comment by davidgovea** [comment]
glad you like em.. I'm putting together a more flexible test page where you can view time/frequency domains, apply effects, and play back the signal.  Eventually want to be able to generate filter response bode plots as well

**Comment by jussi-kalliokoski** [comment]
Sounds good! I've been thinking of including the frequency response plots for the filters as well. Maybe a general purpose testing template could be nice.

**Pull request merged**
