### PR TITLE
browserify build + commonJS require + restructuring

### PR DESCRIPTION
**Pull request by sebpiq**
Another messy commit. Mostly moving around/renaming files to reflect the `AudioKit` structure.

The interesting part is the browserify build. I have found a hack to integrate scripts loaded with the `<script>` tag (our browser dependencies) to the browserify bundle.

For example, to have underscore available, you just need to include a file that exports it, like so : 

``` javascript
// exposing underscore.js to the browserify bundle
module.exports = window._
```

Those files are created automatically by the task `"browser-dependencies-export"`. It's not super beautiful, but not that complicated either, and most of all it works.

### CODE REVIEW

**Comment by jussi-kalliokoski** [comment]
TBH, looking at this, I don't think it's a good idea to depend on browserify... I don't want to require (or worse yet, bundle) a specific build of underscore and other dependencies (plus requiring browserify). This goes quite far from the goal of minimalism we had in mind.

**Comment by sebpiq** [comment]
>  This goes quite far from the goal of minimalism we had in mind

Look at the file generated : http://pastebin.com/naV5Uwdp
There's nothing special in there, really it's quite ok. **The dependencies are not bundled.** Look line 2 and line 6. The bundle exposes underscore and webarraymath from the `window` object. 
So it's really just like the build system I proposed before, except that it is an established solution.

The fact that it is uses `require` means that we are actually quite independent from our build system (there is a few dozen other build systems that wrap require/exports style modules that could be used instead of browserify).

**Comment by sebpiq** [comment]
Why I am insisting so much on `require` is because it is a standard, it makes the organization of the code very clear and imports are explicit.

As I mentioned, I was first really set off by aurora.js because it uses a lot of custom stuff. The threshold to get started contributing is just too big. I saw that I just gave up. Then, I came back a couple of weeks later, because I really really needed it. 

So I think not using custom stuff and opaque imports is a favour made to the users in making the source code easy to read, and the contribution threshold quite low. It can only be beneficial in the long run.

**Comment by jussi-kalliokoski** [comment]
> The dependencies are not bundled.

Sorry, my bad! I misunderstood big time. -.-

> The threshold to get started contributing is just too big

I see your point, and agree, unfortunately (for aurora.js).

I too am mostly concerned with keeping the amount of work included in starting to use, and especially contributing to the library as small as possible, hence my hesitation.

But fair enough, let's go with this at least for now. If we can think of something better later on, great, but at least this is not a bad foundation to jump from.

**Comment by jussi-kalliokoski** [comment]
BTW, this is more related to the other pull request, but I'm not a big fan of declaring source file names inside the gruntfile. You'll eventually end up needing them somewhere else as well and not being able to reference to them since they're in the grunt configuration only.

**Comment by sebpiq** [comment]
> I see your point, and agree, unfortunately (for aurora.js).

I mean ... it does it's job really well. But maintanablity .... I'm not convinced

> BTW, this is more related to the other pull request, but I'm not a big fan of declaring source file names inside the gruntfile. 

Ok we can move them. Though I don't really see what you would need them for.
Anyways, this is not static! As you said, we can always change later when we find better solution. I think this is fine to start with :)

**Comment by jussi-kalliokoski** [comment]
> But maintanablity .... I'm not convinced

Agreed.

> As you said, we can always change later when we find better solution.

Yes, right you are, and probably better to keep it simple and solve problems when they become problems. :)

**Pull request merged**
