### PR TITLE
#20 bugfix and new Band-Pass Biquad Filter

### PR DESCRIPTION
**Pull request by davidgovea**
Fixed a bug in #20 in the BiquadFilter.reset method..
`self.inputs = self.outputs = [0,0]` wasn't producing expected results

Added new BandPass filter & updated test page with 2 BPF tests

### CODE REVIEW

**Comment by jussi-kalliokoski** [comment]
Otherwise all awesome, but... Do you know some kickass git trick to make it like that library build & revert never happened? :D

**Comment by davidgovea** [comment]
uhhh, looks like I screwed that up.. I'll fix in the morning

**Comment by jussi-kalliokoski** [comment]
Heheh, ok. :)

**Comment by davidgovea** [comment]
almost had it with git-rebase.. borked it though. Starting fresh :/

**Pull request closed without merging**
