### PR TITLE
Pre-Processing test fixes

### PR DESCRIPTION
**Pull request by davidgovea**
- Capper.createBufferBased needed a channel count
- Added lfo generate to capper preprocess for dynamic capping
- Updated title

### CODE REVIEW

**Comment by jussi-kalliokoski** [comment]
Oops! Who tests the tester, right? :D

**Comment by jussi-kalliokoski** [comment]
I used your test as a template, as you probably noticed. :P

**Comment by jussi-kalliokoski** [comment]
Oh, btw, for audiolib.js I've used hard tabs with width of 8 characters. Don't worry about the code you've already written, I'll take care of that, it's a simple `s/    /\t/g` . Sorry for nitpicking! :)

**Comment by davidgovea** [comment]
Thanks, I was having a time trying to get the ='s to line up!

**Comment by jussi-kalliokoski** [comment]
Hehe, np, and sorry for the trouble! I did the replace for source code now, for tests it doesn't really matter that much.

**Pull request merged**
